# Generated by Django 3.1.3 on 2020-11-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parnet',
            new_name='parent',
        ),
    ]
